name: Caller Workflow

on:
  push:



jobs:
  path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'apps/docs/**'
            web:
              - 'apps/web/**'
      - if: steps.filter.outputs.docs == 'true'
        id: service
        run: echo "::set-output name=app::docs"

      - if: steps.filter.outputs.web == 'true'
        id: service
        run: echo "::set-output name=app::web"


  call-workflow-2-in-local-repo:
    if: jobs.path.steps.filter.outputs.docs != ''
    uses: ./.github/workflows/next-ci.yml
    with:
      app: jobs.path.steps.service.outputs.app

