name: Caller Workflow

on:
  push:

jobs:
  call-workflow-2-in-local-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Call Workflow 2 in Local Repo
        uses: ./.github/workflows/called.yaml
        with:
          username: mona
