name: CI

on:
  push:
    branches:
      - main
    paths:
      - packages/**/**

jobs:
  Web-CI:
    uses: ./.github/workflows/next-ci.yml
    with:
      app: web
  Docs-CI:
    uses: ./.github/workflows/next-ci.yml
    with:
      app: docs
