name: APPS_CI
on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/**/**"

env:
  APP: 'web'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:


      - name: call next CI workflow
        uses: ./.github/workflows/next-ci.yml
        with:
          app: 'web'



