name: Caller Workflow

on:
  push:


env:
  APP: 'docs'

jobs:
  check-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'apps/docs/**'
            web:
              - 'apps/web/**'
      - if: steps.filter.outputs.docs == 'true'
        run: echo "APP=docs" >> $GITHUB_ENV

      - if: steps.filter.outputs.web == 'true'
        run: echo "APP=web" >> $GITHUB_ENV

  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/next-ci.yml
    with:
      app: ${{ env.APP }}

