name: Caller Workflow

on:
  push:



jobs:
  path:
    runs-on: ubuntu-latest
    env:
      SERVICE : ''
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'apps/docs/**'
            web:
              - 'apps/web/**'
      - if: steps.filter.outputs.docs == 'true'
        run: echo "SERVICE=docs >> $GITHUB_ENV"

      - if: steps.filter.outputs.web == 'true'
        run: echo "SERVICE=web >> $GITHUB_ENV"


  call-workflow-2-in-local-repo:
    if: jobs.path.env.SERVICE != ''
    uses: ./.github/workflows/next-ci.yml
    with:
      app: jobs.path.env.SERVICE

