name: Reusable Workflow

on:
  push:
  workflow_call:
    inputs:
      username:
        required: true
        type: string


jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.username }}
          echo sed 's/./& /g' 
