name: FRONT CI
on:
  pull_request:
    branches:
      - main
    paths:
      - apps/**/**

defaults:
  run:
    shell: bash

env:
  SERVICE: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: install yarn
      run: npm install -g yarn

    - name : yarn install
      run: yarn install

    - name: yarn test
      run: yarn turbo --filter=web test

    - name: Collect
      run: yarn merge

    - name: jest coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        custom-title: Coverage report for Package
        skip-step: all
        coverage-file: merged-report.json
        base-coverage-file: merged-report.json
