name: Next CI
on:
  workflow_call:
    inputs:
      app:
        description: 'Service Name'
        required: true
        type: string



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: install yarn
      run: npm install -g yarn

    - name : yarn install
      run: yarn install

    - name: yarn test
      working-directory: ./apps/${{ inputs.app }}
      run: yarn test

    - name: build
      working-directory: ./apps/${{ inputs.app }}
      run: yarn build

    - name: jest coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        package-manager: yarn
        working-directory: ./apps/{{ inputs.app }}
        coverage-file: report.json
        base-coverage-file: report.json
